# Generated by Claude at omni_python_dbapi. Verify against code. May be stale.
"""SQLAlchemy dialect compliance suite, wired against our dialect.

Run from inside plpy via omni_python_sqlalchemy.runner.run_compliance().
"""
