# Generated by Claude at omni_python_dbapi. Verify against code. May be stale.
"""Bootstrap SA's pytest plugin and register our dialect.

The dialect entrypoint is also registered via setuptools in pyproject.toml,
but registry.register() here makes the suite self-contained so it runs even
without the entrypoint being installed.
"""

import pytest
from sqlalchemy.dialects import registry

registry.register(
    "postgresql.omni_python",
    "omni_python_sqlalchemy",
    "PGDialect_omni_python",
)

pytest.register_assert_rewrite("sqlalchemy.testing.assertions")

from sqlalchemy.testing.plugin.pytestplugin import *  # noqa: F401,F403,E402
