# Generated by Claude at omni_python_dbapi. Verify against code. May be stale.
"""Dialect compliance requirements for omni_python (inside-PG SA dialect).

Starts from SA's standard SuiteRequirements and turns OFF anything plpy
can't model. We are conservative on purpose: it is easier to open a
requirement back up after a green run than to chase mysterious failures.

Disabled groups, with rationale:

- Anything that needs a second concurrent connection (savepoint isolation
  tests that open two connections, two-phase commit, listen/notify across
  sessions, sequencing tests that depend on cross-connection visibility).
  We have exactly one in-process connection.
- Real DBAPI disconnects / reconnects. There is no socket to drop.
- Server-side cursors. plpy SPI returns full result sets.
- Anything depending on `SET LOCAL` / per-connection GUCs surviving across
  separate connections. Our connect() returns a fresh in-process state but
  all of it shares the calling backend's session settings.
- AUTOCOMMIT isolation level. plpy is always in a transaction.
"""

from sqlalchemy.testing import exclusions
from sqlalchemy.testing.requirements import SuiteRequirements


class Requirements(SuiteRequirements):

    # ---- in-process connection limits -----------------------------------

    @property
    def independent_connections(self):
        return exclusions.closed()

    @property
    def graceful_disconnects(self):
        return exclusions.closed()

    @property
    def two_phase_transactions(self):
        return exclusions.closed()

    @property
    def server_side_cursors(self):
        return exclusions.closed()

    @property
    def isolation_level(self):
        # plpy runs inside the caller's transaction; we can't switch levels.
        return exclusions.closed()

    @property
    def autocommit(self):
        # No AUTOCOMMIT isolation level inside plpy.
        return exclusions.closed()

    # ---- features we DO support (override pg8000 closed defaults) -------

    @property
    def returning(self):
        return exclusions.open()

    @property
    def insert_returning(self):
        return exclusions.open()

    @property
    def update_returning(self):
        return exclusions.open()

    @property
    def delete_returning(self):
        return exclusions.open()

    @property
    def array_type(self):
        return exclusions.open()

    @property
    def json_type(self):
        return exclusions.open()

    @property
    def uuid_data_type(self):
        return exclusions.open()
