# Generated by Claude at omni_python_dbapi. Verify against code. May be stale.
"""In-process runner for SQLAlchemy's dialect compliance suite.

`run_compliance()` is meant to be called from inside a plpy function. It
invokes pytest against the bundled compliance suite, captures each test's
outcome via a small inline pytest plugin, and returns a JSON-serializable
dict with pass/fail/skip counts plus a list of failures.
"""

import contextlib
import io
import json
import os
import sys


def _compliance_dir():
    return os.path.join(os.path.dirname(__file__), "_compliance")


class _OutcomeCollector:
    """pytest plugin that records every test's final outcome."""

    def __init__(self):
        self.passed = []
        self.failed = []
        self.skipped = []
        self.errors = []

    def pytest_runtest_logreport(self, report):
        if report.when == "call":
            if report.passed:
                self.passed.append(report.nodeid)
            elif report.failed:
                self.failed.append({
                    "nodeid": report.nodeid,
                    "longrepr": str(report.longrepr)[:2000],
                })
            elif report.skipped:
                reason = ""
                if isinstance(report.longrepr, tuple) and len(report.longrepr) >= 3:
                    reason = str(report.longrepr[2])
                self.skipped.append({"nodeid": report.nodeid, "reason": reason})
        elif report.when in ("setup", "teardown") and report.failed:
            self.errors.append({
                "nodeid": report.nodeid,
                "when": report.when,
                "longrepr": str(report.longrepr)[:2000],
            })


def run_compliance(node_filter=None, max_failures=None, verbose=False):
    """Run SA's compliance suite. Returns a dict.

    node_filter: pytest -k expression to narrow what runs. None = all.
    max_failures: pytest --maxfail value. None = no limit.
    verbose: emit per-test lines to plpy.notice (slow, useful for debug).
    """
    import pytest

    suite_dir = _compliance_dir()
    collector = _OutcomeCollector()

    argv = [
        "--rootdir", suite_dir,
        "-c", os.path.join(suite_dir, "setup.cfg"),
        "--dburi", "postgresql+omni_python://",
        # pytest's default fd-level capture confuses plpy's stdout handling.
        # We do our own redirect_stdout outside.
        "--capture=no",
        os.path.join(suite_dir, "test_suite.py"),
    ]
    if node_filter:
        argv += ["-k", node_filter]
    if max_failures is not None:
        argv += ["--maxfail", str(max_failures)]
    if not verbose:
        argv += ["-q", "--no-header"]

    cwd = os.getcwd()
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    try:
        os.chdir(suite_dir)
        with contextlib.redirect_stdout(stdout_buf), contextlib.redirect_stderr(stderr_buf):
            exit_code = pytest.main(argv, plugins=[collector])
    finally:
        os.chdir(cwd)

    summary = {
        "exit_code": int(exit_code),
        "passed": len(collector.passed),
        "failed": len(collector.failed),
        "skipped": len(collector.skipped),
        "errors": len(collector.errors),
        "failures": collector.failed,
        "errors_detail": collector.errors,
        "stdout_tail": stdout_buf.getvalue()[-4000:],
        "stderr_tail": stderr_buf.getvalue()[-4000:],
    }

    # Always surface the headline so it lands in pg_yregress TAP output even
    # when the caller's assertions are loose.
    try:
        import plpy
        plpy.notice(
            f"SA compliance: exit={summary['exit_code']} "
            f"passed={summary['passed']} failed={summary['failed']} "
            f"skipped={summary['skipped']} errors={summary['errors']}"
        )
    except Exception:
        pass

    # If a writable host-shared dir is mounted, dump the full JSON for offline
    # inspection. Best effort only.
    for candidate in ("/omni/.sa_compliance_last.json", "/tmp/sa_compliance_last.json"):
        try:
            with open(candidate, "w") as f:
                json.dump(summary, f, indent=2)
            break
        except Exception:
            continue

    return summary


def run_compliance_json(node_filter=None, max_failures=None):
    """Same as run_compliance, but returns a JSON string. Convenient for
    yregress scenarios that want to assert against a single text column."""
    return json.dumps(run_compliance(node_filter=node_filter, max_failures=max_failures))
